server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: task-query-service
          uri: lb://task-query-service
          predicates:
            - Path=/tasks/**
        - id: board-service
          uri: lb://board-service
          predicates:
            - Path=/boards/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
